---

stages:
  - lint
  - deployment test

before_script:
  - ansible --version
  - molecule --version
  - ansible-config dump --only-changed

Ansible lint:
  stage: lint
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - ansible-lint . -c .ansible-lint
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - delegated

Docker Solr:
  stage: deployment test
  script:
    - molecule test -s default
  tags:
    - docker

EPC Solr:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-delegated
  tags:
    - delegated

.EPC Windows Solr:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-windows
  tags:
    - delegated

AWS Solr:
  variables:
    EPC_REGION: AWS-EUCENTRAL
  stage: deployment test
  script:
    - molecule test -s cloud-aws-delegated
  tags:
    - delegated
