---
- name: Install ansible selinux configure libraries
  package:
    name:
      - policycoreutils-python
      - libsemanage-python
    state: present
  register: installed_packages
  until: installed_packages is succeeded
  become: true
  when: ansible_selinux.status == 'enabled'

- name: Enable connections to HTTP port
  seport:
    ports: '{{ solr_port }}'
    proto: tcp
    setype: http_port_t
    state: present
  become: true
  when:
    - ansible_selinux.status == 'enabled'
    - ansible_selinux.mode != 'disabled'
