---
- name: Enable EPEL repository
  yum:
    name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm'
    state: present
  register: installed_packages
  until: installed_packages is succeeded
  become: true

- name: Choose system based task
  include_tasks: '{{ ansible_system }}.yml'

- name: Add selinux support
  include_tasks: ../selinux-support.yml
  when:
    - ansible_selinux.status == 'enabled'
