---
- name: Enable EPEL repository
  yum:
    name: 'https://archives.fedoraproject.org/pub/archive/epel/7/x86_64/Packages/e/epel-release-7-14.noarch.rpm'
    state: present
  register: installed_packages
  until: installed_packages is succeeded
  become: true

- name: Choose system based task
  include_tasks: '{{ ansible_system }}.yml'

- name: Add selinux support
  include_tasks: ../selinux-support.yml
  when:
    - ansible_selinux.status == 'enabled'
