---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:

  - name: test-aws-centos7-solr-standalone-solr7
    image: ami-9887c6e7
    platform: centos7
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - solr7
      - java8_nix

  - name: test-aws-centos7-solr-standalone
    image: ami-9887c6e7
    platform: centos7
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - java12_nix

  - name: test-aws-ubuntu16-solr-standalone
    image: ami-09677e0a6b14905b0
    platform: ubuntu16
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    security_group_name:
      - default
    spot_price: 0.04
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - java8_nix

  - name: test-aws-ubuntu18-solr-standalone-solr7
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    security_group_name:
      - default
    spot_price: 0.04
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - solr7
      - java12_nix

  - name: test-aws-Debian9-solr-standalone
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - java12_nix

  - name: test-aws-Windows2016-solr-standalone
    image: ami-00a20f508263efd30
    platform: windows2016core
    region: us-east-1
    instance_type: m5a.large
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.14
    security_group_name:
      - default
    wait_timeout: 1800
    groups:
      - windows
      - solr7
      - java8_win

  - name: test-aws-Windows2019-solr-standalone
    image: ami-0477b9335a5a75438
    platform: windows2019core
    region: us-east-1
    instance_type: m5a.large
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.14
    security_group_name:
      - default
    wait_timeout: 1800
    groups:
      - windows
      - java12_win

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      solr7:
        solr_version: 7.7.1
      java8_nix:
        transport: web
        transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-java/jdk-8u211-linux-x64.tar.gz"
        java_major_version: 8
        java_minor_version: 211
        java_package: jdk
        java_tarball_install: true
      java8_win:
        transport: web
        transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-java/jdk-8u152-windows-x64.exe"
        java_major_version: 8
        java_minor_version: 152
        java_package: jdk
        java_tarball_install: false
      java12_nix:
        solr_use_java_version_8: false
      java12_win:
        solr_use_java_version_8: false
        java_distribution: openjdk
        transport: chocolatey
        java_major_version: 12
        java_minor_version: 0.2
      windows:
        ansible_connection: winrm
        ansible_password: "{{ lookup('env', 'WINRM_ADMIN_PWD') | default('M0leCule123!', true) }}"
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../resources/provisioning/AWS/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-direct
verifier:
  name: ansible
  lint:
    name: ansible-lint
