---
- name: Verify Linux
  hosts: rhel_family
  tasks:

  - name: Check Solr service status
    service:
      name: 'solr'
    check_mode: true
    register: sorl_status

  - name: Solr service debug
    debug:
      var: sorl_status

  - name: Solr status
    assert:
      that: "'running' == sorl_status.status.SubState"

- name: Verify Windows
  hosts: windows
  tasks:

  - name: Check Solr service status
    win_service:
      name: 'solr'
    check_mode: true
    register: sorl_status

  - name: Solr service debug
    debug:
      var: sorl_status

  - name: Solr status
    assert:
      that: "'running' == sorl_status.state"
