---
- name: Verify
  hosts: all
  tasks:

  - name: Check Solr service status
    service:
      name: 'solr'
      state: started
      enabled: yes
    register: sorl_status

  - name: Solr service debug
    debug:
      var: sorl_status

  - name: Solr status
    assert:
      that: "'running' == sorl_status.status.SubState"
