---
- name: Export certificate and private key into a bundle
  command: >-
    openssl pkcs12 -export
    -in '{{ local_cert_file_path }}/{{ solr_local_cert_file_name }}'
    -inkey '{{ local_pkey_file_path }}/{{ solr_local_pkey_file_name }}'
    -name '{{ ansible_hostname }}'
    -passout pass:{{ solr_ssl_key_store_password }}
    -out '{{ ansible_hostname }}.p12'
  args:
    chdir: '{{ solr_ssl_key_store_path }}/'
    creates: '{{ ansible_hostname }}.p12'
  become: True
  become_flags: '-i'
  become_method: sudo

- name: Import the PKCS12 file into a new java keystore
  java_cert:
    pkcs12_path: '{{ ansible_hostname }}.p12'
    pkcs12_password: '{{ solr_ssl_key_store_password }}'
    keystore_path: '{{ solr_ssl_key_store_name }}'
    keystore_pass: '{{ solr_ssl_key_store_password }}'
    keystore_create: True
    state: present
  become: True
