---
- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.java
      transport: web
      transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-java/jdk-8u211-linux-x64.tar.gz"
      java_major_version: 8
      java_minor_version: 211
      java_package: jdk
      java_tarball_install: True
    - role: ansible-role-solr-standalone
  vars:
    solr_change_default_password: False
    solr_copy_default_configsets: True
